version: '3.7'

services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "djangoApp"

  backend:
    build: .
    image: djangoapp
    command: sh ./djangoApp/entrypoint.sh
    environment:
      DJANGO_DEBUG: 1
      DJANGO_SETTINGS_MODULE: project.settings_local
    volumes:
      - .:/code/
    ports:
      - 8000:8000
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/local/app
      - /usr/local/app/node_modules
    ports:
      - 8080:8080

volumes:
  postgres_data: